# To stop: docker-compose down --remove-orphans -v

version: '3.8'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:33060
    volumes:
    - mysql:/var/lib/mysql
    - ./infrastructure/dev/database-dev.sql:/docker-entrypoint-initdb.d/database-dev.sql

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
    - 8080:8080
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      #KEYCLOAK_DEFAULT_THEME:
      KEYCLOAK_IMPORT: /tmp/realm-admin.json,/tmp/realm-customers.json
    volumes:
    - ./infrastructure/dev//realm-admin.json:/tmp/realm-admin.json
    - ./infrastructure/dev//realm-customers.json:/tmp/realm-customers.json


volumes:
  mysql: