# Stop:  docker-compose down --remove-orphans -v
# Login: docker exec -it -u root keycloak /bin/bash
version: '3.8'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:33060
    volumes:
    - mysql:/var/lib/mysql
    - ./infrastructure/dev/database-dev.sql:/docker-entrypoint-initdb.d/database-dev.sql:ro

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
    - 8080:8080
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      # KEYCLOAK_DEFAULT_THEME: /opt/jboss/keycloak/themes/my-theme/
      KEYCLOAK_IMPORT: /tmp/realm-admin.json,/tmp/realm-customers.json
    volumes:
    - ./infrastructure/dev/realm-admin.json:/tmp/realm-admin.json:ro
    - ./infrastructure/dev/realm-customers.json:/tmp/realm-customers.json:ro
    # - ./infrastructure/my-theme:/opt/jboss/keycloak/themes/my-theme/:ro


volumes:
  mysql: