# Stop:  docker-compose down --remove-orphans -v
# Login: docker exec -it -u root keycloak /bin/bash
# /opt/jboss/keycloak/bin/standalone.sh -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/file.json -Djboss.socket.binding.port-offset=100
# /opt/jboss/keycloak/bin/add-user.sh
version: '3.8'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:33060
    volumes:
    - mysql:/var/lib/mysql
    - ./infrastructure/dev/database-dev.sql:/docker-entrypoint-initdb.d/database-dev.sql:ro

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
    - 8180:8080
    depends_on:
      - mysql
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      # KEYCLOAK_DEFAULT_THEME: /opt/jboss/keycloak/themes/my-theme/
      KEYCLOAK_IMPORT: /tmp/realm-app.json
    volumes:
    - ./infrastructure/dev/realm-app.json:/tmp/realm-app.json:ro
    - ./infrastructure/dev/startup-scripts:/opt/jboss/startup-scripts:ro
    # - ./infrastructure/my-theme:/opt/jboss/keycloak/themes/my-theme/:ro


volumes:
  mysql:
